openshift-online/ocm-cli

- CHANGES.adoc
- pkg/info/info.go
> Release 0.1.20

- .gitignore
- Makefile
- build_deploy.sh
This patch add a new `build_deploy.sh` script that builds the binaries
of the project for all the supported platforms (currently _Linux_ and
_macOS_).
> Add `build_deploy.sh` script

- cmd/ocm/delete/cmd.go
- cmd/ocm/get/cmd.go
- cmd/ocm/patch/cmd.go
- cmd/ocm/post/cmd.go
Currently when the HTTP commands receive an error response they return
an error, and as a result the main program prints the usage message.
This isn't correct; we should just print the returned response and exit
with an error code.
> Don't print usage for HTTP errors

- cmd/ocm/cluster/list/list.go
`version.id` points to the originally deployed version, where as `openshift_version` displays the current version reported via telemetry
> Change default version field to point to current version

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes in this version are the following:
- Change default version field to point to current version.
- Add ability to open the console URL in browser.
> Release 0.1.22

- cmd/ocm/account/quota/cmd.go
Based on a recommendation from @abhgupta, change the field that the `ocm account quota` looks at, so that we can accurately report the quota of the specified organization.
```
Cluster quota for organization 'Example Organization' ID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
MULTI-AZ: 0/15
SINGLE-AZ: 11/15
SINGLE-AZ BYOC: 1/1
```
> Fix quota output to look at correct API field

- cmd/ocm/cluster/describe/describe.go
- go.mod
- go.sum
The more relevant change in the new version of the SDK is that the
`cluster.craetor` field has been removed. This means that we need to
update the `cluster describe` command to get the creator following the
link to the subscription and then to the account.
Related: https://jira.coreos.com/browse/SDA-1395
> Update to SDK 0.1.36

- CHANGES.adoc
- pkg/info/info.go
- Fixed the `cluster create` command so that it retrieves all the enabled
versions.
> Release 0.1.26

- CHANGES.adoc
- pkg/info/info.go
- Added `oc cluster versions` command.
> Release 0.1.27

- pkg/dump/dump.go
Currently when a response body is empty the tool will still print it,
followed by a blank line. This patch changes it so that it will not
print it at all.
> Don't print empty response body

- Makefile
- README.adoc
- cmd/ocm/login/cmd.go
- go.mod
- go.sum
This patch drops support for authenticating with
_developers.redhat.com_, as that has already been removed from the
server and from the SDK.
> Drop support for _developers.redhat.com_

- CHANGES.adoc
- pkg/info/info.go
- Dropped support for _developers.redhat.com_.
> Release 0.1.28

- CHANGES.adoc
- pkg/info/info.go
- Allow bare `ocm login` to suggest the token page without extra noise.
> Release 0.1.29

- README.adoc
This patch adds to the `README.adoc` file explanations of how to use the
RPM packages built with _Fedora Copr_ and how to update that build
configuration when needed.
Related: https://jira.coreos.com/browse/SDA-1595
> Explain how to use and build RPMs

- cmd/ocm/account/status/cmd.go
Example output
```
$ go run cmd/ocm/main.go account status
User aweiteka-srep on https://api.stage.openshift.com in org 'Red Hat OpenShift Online' 1HELaFOf2YHWwwvt3XMbT5Mja7M (external_id: 6323660)
Roles: SuperAdmin, SREP, UHCSupport, RHUser, ClusterOwner, OrganizationMember, AuthenticatedUser
```
> add org details to account status cmd

- cmd/ocm/cluster/describe/describe.go
- go.mod
- go.sum
The more relevant changes in the new version of the SDK are the
following:
- Use JSON iterator instead of the default JSON Go package.
> Update to SDK 0.1.78

- cmd/ocm/account/status/cmd.go
- cmd/ocm/account/users/cmd.go
- pkg/account/account.go
Adding options needed by SRE Security for quarterly compliance review processes.
Now ocm gives us the ability to sift through the entirety of the user base and find those with specific roles in under a minute.
Every 3 months, we'll run a beefy query like the following:
ocm account users --roles="role1,role2,role3" --workers=100 --pagesize=100000
> adding new options for "ocm account users" command

- README.adoc
- pkg/config/config.go
Implements #48 with a global var. I'd also do `--config`, but there's no existing global param support in the code, so figuring out the proper structures is non–trivial for someone new to the code.
This, on the other hand, is a very small patch.
> Add OCM_CONFIG env var support

- CHANGES.adoc
- pkg/info/info.go
- Add number of _infra_ nodes to the output of the `cluster describe` command.
- Add `--roles` flag to the `account users` command.
- Add support for `OCM_CONFIG` environment variable to indicate an alternative
location of the configuration file.
- Tighten output of the `account orgs`, `account quota`, `account users` and
`cluster list` commands.
> Release 0.1.34

- cmd/ocm/account/quota/cmd.go
before patch:
```
-AZ: 0/20 addon-rhmi-operator
MULTI-AZ: 0/15 m5.xlarge
SINGLE-AZ: 13/100 m5.xlarge
SINGLE-AZ BYOC: 0/15 m5.xlarge
```
After patch:
```
0/20 addon-rhmi-operator 
0/15 m5.xlarge MULTI
13/100 m5.xlarge SINGLE
0/15 m5.xlarge SINGLE BYOC
```
> display quota so it supports add-ons

- cmd/ocm/cluster/list/list.go
This will make it easier to see when a cluster has completed installing, or when a cluster is stuck in an uninstalling state.
> Add 'state' to list of default columns for cluster list

- go.mod
- go.sum
- pkg/dump/dump.go
This patch changes the SDK so that it preserves the order of attributes
of output JSON documents.
> Preserve JSON order

- CHANGES.adoc
- go.mod
- go.sum
- pkg/info/info.go
- Add `state` to list of default columns for cluster list.
- Preserve order of attributes in JSON output.
> Release 0.1.36

- cmd/ocm/cluster/describe/describe.go
- pkg/cluster/describe.go
This patch changes the `cluster describe` command so that it searches by
name, identifier and external identifier. For example, if a cluster is
named `mycluster`, has identifier `123` and external identifier
`87cc8272-0ec4-444b-ae2c-baf97acbcf7a` then these three commands will
return the same result:
```
$ ocm cluster describe mycluster
$ ocm cluster describe 123
$ ocm cluster describe 87cc8272-0ec4-444b-ae2c-baf97acbcf7a
```
The patch also adds the external identifier to the output of the
command, so it will look like this:
```
$ ./ocm cluster describe mycluster
ID:          123
External ID: 87cc8272-0ec4-444b-ae2c-baf97acbcf7a
Name:        mycluster.a0b1.p1.openshiftapps.com
API URL:     https://api.mycluster.a0b1.p1.openshiftapps.com:6443
Masters:     3
Computes:    4
Region: …
```
> Describe by name, identifier or external identifier

- cmd/ocm/account/orgs/cmd.go
- cmd/ocm/cluster/create/create.go
- cmd/ocm/cluster/list/list.go
- cmd/ocm/delete/cmd.go
- cmd/ocm/get/cmd.go
- cmd/ocm/main.go
- cmd/ocm/patch/cmd.go
- cmd/ocm/post/cmd.go
- pkg/arguments/arguments.go
Currently the raw HTTP methods don't support correctly query parameters.
This patch fixes that.
Related: https://github.com/openshift-online/ocm-cli/issues/6
> Support query parameters in raw HTTP methods

- cmd/ocm/cluster/create/create.go
- pkg/cluster/describe.go
Now that we have maximum expiration support in the OCM API, this makes it easy to specify an expiration date via the CLI for a cluster you are creating. You can specify an exact date in RFC3389 format, or you can choose a duration (like 8h or 2d).
> Add support for expiration in ocm cluster create

- pkg/cluster/describe.go
This PR adds the console URL to the describe output to support SRE who require easy access to the console URL for cluster access.
> Add console URL to describe

- cmd/ocm/cluster/create/create.go
- pkg/cluster/describe.go
This adds support for specifying a cloud provider to `ocm cluster create` via a `--provider` flag
> Add support for specifying cloud provider

- cmd/ocm/cluster/login/login.go
https://github.com/drewandersonnz/ocm-container
I want to use OCM outside of my normal environment where browser.OpenURL is not possible.
Specifically I use OCM inside of an ephemeral container where it is isolated from the rest of my host OS.
Outputting the Console URL allows me to copy/paste or simply click the link from within the terminal window.
Accidentally closed https://github.com/openshift-online/ocm-cli/pull/73
> Output Console URL for use in ocm-container

- cmd/ocm/delete/cmd.go
- cmd/ocm/get/cmd.go
- cmd/ocm/patch/cmd.go
- cmd/ocm/post/cmd.go
- pkg/urls/url_expander.go
- pkg/urls/url_expander_test.go
This PR adds shell auto-completion for resources which can be used by the "get", "delete", "patch" and "post" commands. This reduces the need for OCM users to memorize API URLs, and promotes the use of the already-existing resource shortcuts.
For example, once the bash completion script is generated and sourced:
`ocm get a<tab><tab>`
will output:
`account   accounts  acct      accts`
> Add shell completion for resources

- cmd/ocm/config/cmd.go
- cmd/ocm/config/get/get.go
- cmd/ocm/config/set/set.go
- pkg/config/config.go
As a noob, I was frustrated by the (lack of) docs produced by `ocm
config --help`, so this commit improves on that by:
- describing how/where we look for the config file;
- printing a table of supported variables with a brief description of
each;
- adding a reference back to 'ocm config --help' from 'ocm get --help'
and 'ocm set --help'.
In the future, it would be nice to improve on the help strings
themselves, and deduplicate them with the help strings for the 'ocm
login' flags (whence most of this commit's help strings were stolen).
> config: beef up help message

- cmd/ocm/cluster/list/list.go
This allows the user to pass either `--managed` or `--managed=true` to
filter on managed clusters, or `--managed=false` to filter on non-managed
clusters. Skipping the flag will show both managed and non-managed
clusters.
> list: Allow setting --managed=false

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes in the new release are the following:
- Add support for expiration in ocm cluster create.
- Add support for specifying cloud provider.
- Add cloud provider to default columns.
- config: beef up help message.
- Add console URL to describe.
- Output Console URL.
- Add shell completion for resources.
- Add API Listening to cluster descrribe.
- Update to ocm-sdk-go 0.1.105
- Allow setting --managed=false in cluster list.
> Release 0.1.38

- pkg/cluster/describe.go
> Don't fail "cluster describe" if a user is unauthorized to get account

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/create/cmd.go
- cmd/ocm/describe/cluster/cmd.go
- cmd/ocm/describe/cmd.go
- cmd/ocm/list/cluster/cmd.go
- cmd/ocm/list/cmd.go
- cmd/ocm/main.go
Added describe, list and create cluster commands.
This is the first part of changing `ocm-cli` commands to align with other k8s tools.
> Align cluster commands to other k8s tools

- README.adoc
The currently documented curl command returns a 302:
```
$ curl -sI https://github.com/openshift-online/ocm-cli/releases/download/v0.1.30/ocm-linux-amd64|grep ^status
status: 302 Found
```
> curl follows redirects to download the binary

- pkg/cluster/describe.go
Adds the provision shard to `ocm describe cluster`
> Display provision shard name in describe cluster

- cmd/ocm/tunnel/cmd.go
This command parameters change for every cluster, however I have a need to transfer the `sshuttle` execution out of my tool `ocm-container` https://github.com/drewandersonnz/ocm-container where `ocm` lives within ephemeral containers.
Example:
```
ocm tunnel -c xzy123
Will create tunnel to cluster:
Name: cluster
ID: xyz123
client: Connected.
```
> Output sshuttle command execution string for review

- cmd/ocm/cluster/login/login.go
* Simplify login to clusters when login via the CLI is not possible
(e.g. GCP IDP)
* Use `--browser` flag to get to the token page directly
> Simplify cluster login via browser

- cmd/ocm/cluster/login/login.go
this is useful if you are running inside a container without browser access and want that url for external login
> doc(login.sh): add printf before login

- cmd/ocm/cluster/login/login.go
Currently it's `ocm cluster login --browser`, but the page that redirects to displays the API token, hence `--token` feels more fitting.
Also, in practice this will be mostly used to log in via CLI, so `--browser` is sort of the opposite of what one would use it for.
> Use `--token` as argument for `cluster login`

- go.mod
- pkg/arguments/arguments.go
https://issues.redhat.com/browse/SDA-2723
This addresses the usability problem that when using `post` or `patch` and one forgets a body is needed, the command just appears to hang (as it's waiting for input and EOF).  Now it'll print a message to stderr explaining what happens and why:
<pre>
<b>$ ./ocm post /api/authorizations/v1/self_access_review | jq .</b>
No --body file specified, reading request body from stdin:
<b>{"resource_type": "Subscription", "action": "get"}</b>
<kbd><b>Ctrl+D</b></kbd>
{
"account_id": "1Du28axTYfDk2r9fHOUGSoo5GZa",
"resource_type": "Subscription",
"action": "get",
"allowed": true
}
</pre>
Composing JSON on stdin is not really convenient; typically one would send it by redirection / pipe.
In these cases we don't print the message:
```sh
$ echo …
```
> Show hint when waiting for body from stdin interactively

- cmd/ocm/list/cmd.go
- cmd/ocm/list/version/cmd.go
@igoihman tiny fix, please review.
Followup to #152.  Wrong import caused it to offer:
$ ./ocm list --help
...
version     Prints the version
$ ./ocm list version
0.1.43
now does:
$ ./ocm list --help
...
versions    List available versions
$ ./ocm list versions
4.3.25
4.4.11
...
$ ./ocm list version
4.3.25
4.4.11
...
Added list version = list versions alias and changed package name to singular for consistency with sibling commands.
> Use correct implementation for `ocm list version`

- cmd/ocm/tunnel/cmd.go
if the cluster id is the only parameter for the command, I think it is better to pass the cluster_id directly without `--cluster` for easy use.
@cblecker Please help take a look.
> use the cluster id directly without --cluster

- cmd/ocm/tunnel/cmd.go
Uses a < instead of != in order to allow execution with sshuttle arguments.  As it stands, attempting to run `ocm tunnel [cluster-name] -- --dns` no longer works as it errors out here.
> Use gt to allow for sshuttle arguments.

- .golangci.yml
- cmd/ocm/cluster/create/create.go
- cmd/ocm/create/cluster/cmd.go
- pkg/cluster/cluster.go
Alternative to #180.
1. Drops --parameter and --header flags from `cluster create` and `create cluster` commands.
These never worked in these 2 commands, and it makes sense to only have them in lower-level REST commands like `ocm post`.
2. Adds `ocm create cluster --dry-run` flag.
```
$ go run ./cmd/ocm create cluster beni-7 --dry-run --region=wrong
Error: Failed to create cluster: dry run: unable to create cluster: identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is '1h007pdkir8834u880ea7bblut6nan3k': Region 'wrong' is not supported for cloud provider 'aws'
exit status 1
$ go run ./cmd/ocm create cluster beni-7 --dry-run 
dry run: Would be successful.
```
In debug mode, the successful case shows a confusing `Error: Failed to create cluster: dry run: unable to …
> ocm create cluster --dry-run

- cmd/ocm/list/region/cmd.go
We are planning to remove the display name from the UI so I'd like the CLI to match the same behavior
> remove region display name

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/list/version/cmd.go
- go.mod
- go.sum
- pkg/cluster/versions.go
`ocm list versions` dumb lexicographic order had anomalies e.g. 0 < 10 ... 19 < 2:
```
...
4.5.0-rc.6-candidate
4.5.0-rc.7-candidate
4.5.10-candidate
4.5.11
4.5.11-candidate
4.5.11-fast
4.5.12-candidate
4.5.12-fast
4.5.13-candidate
4.5.13-fast
4.5.14-candidate
4.5.14-fast
4.5.15-candidate
4.5.15-fast
4.5.16
4.5.16-candidate
4.5.16-fast
4.5.17-candidate
4.5.17-fast
4.5.18-candidate
4.5.18-fast
4.5.19-candidate
4.5.19-fast
4.5.1-candidate
4.5.1-rc.0-candidate
4.5.2-candidate
4.5.3-candidate
...
```
```
$ go run ./cmd/ocm list versions
4.3.0-0.nightly-2020-11-14-031737-nightly
4.3.0-0.nightly-2020-11-16-145655-nightly
4.3.0-0.nightly-2020-11-17-155059-nightly
4.3.0-0.nightly-2020-11-17-175553-nightly
4.3.0-0.nightly-2020-11-17-213914-nightly
4.4.0-0.nightly-2020-11-13-005352-nightly …
```
> list versions: sort by SemVer, show default

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/create/machinepool/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
- pkg/provider/machine_types.go
Extracted from WIP #181.
The new argument helper will make more sense after I add the other interactive ones; I included it here only to support the removal of a separate `ValidateMachineType` function.
@igoihman @vkareh please review.
```diff
-Error: Expected a valid machine type: A valid machine type number must be specified
-Valid machine types: m5.xlarge r5.xlarge m5.2xlarge c5.2xlarge r5.2xlarge m5.4xlarge c5.4xlarge r5.4xlarge
+Error: A valid --compute-machine-type must be specified.
+Valid options: [m5.xlarge r5.xlarge m5.2xlarge c5.2xlarge r5.2xlarge m5.4xlarge c5.4xlarge r5.4xlarge]
```
```
Error: required flag(s) "instance-type" not set
```
```diff
-Error: Expected a valid machine type: A valid machine type number must be specified
-Valid machine types: m5.xlarge r5.xlarge …
```
> refactor machine types helpers

- pkg/arguments/arguments.go
Revert import that I guess was changed accidentally in #192?
https://github.com/onsi/ginkgo/tree/master/reporters/stenographer/support/go-isatty/ is an older, unmaintained, copy of upstream https://github.com/mattn/go-isatty/
@igoihman please confirm.
> Correct upstream import of go-isatty

- cmd/ocm/create/cluster/cmd.go
- pkg/cluster/cluster.go
Provider id can be "aws", never "AWS".  The wrong comparison caused the CCS code to always send GCP fields, and never send AWS fields, resulting in error :boom::
```
$ go run ./cmd/ocm create cluster cben-5 --dry-run --ccs --aws-access-key-id=AKIA3EM67QKY33CSWLMK --aws-secret-access-key=(cat ~/.aws/credentials | grep aws_secret_access_key | cut --delimiter=' ' --fields=3 | tr -d \n) --debuggo run ./cmd/ocm create cluster cben-5 --dry-run --ccs --aws-account-id=765374464689 --aws-access-key-id=AKIA3EM67QKY33CSWLMK --aws-secret-access-key=(cat ~/.aws/credentials | grep aws_secret_access_key | cut --delimiter=' ' --fields=3 | tr -d \n) --debug
...
I1221 20:00:21.217566  369671 dump.go:136] Request body follows
I1221 20:00:21.218108  369671 dump.go:258] {
"kind": "Cluster",
"api": { …
```
> Fix `ocm create cluster --ccs --provider=aws`

- .goreleaser.yaml
- README.adoc
- cmd/ocm/completion/cmd.go
Already had bash, now also supports zsh, fish, powershell.
Tested on fish, bash, zsh:
[![asciicast](https://asciinema.org/a/381735.svg)](https://asciinema.org/a/381735)
> ocm completion: support other shells

- cmd/ocm/list/version/cmd.go
```
$ ocm list versions --default
4.6.9
$ ocm list versions -h
List the versions available for provisioning a cluster
Usage:
ocm list versions [flags]
Aliases:
versions, version
Examples:
ocm list versions
Flags:
-d, --default   Show the default version
-h, --help      help for versions
```
> print default version in version list

- cmd/ocm/create/cluster/cmd.go
@igoihman @nimrodshn @jhernand one prompt I forgot from #181.
<pre>
...
? Service CIDR: 
? Pod CIDR: 
? Host prefix: 0
<b>? Private cluster (optional): [? for help] (y/N) </b>
</pre>
The wording with "(optional)" copied from `rosa`.
> ocm create cluster --interactive: Prompt for --private

- cmd/ocm/login/cmd.go
This updates the URL to use the proper integration API URL in the login helpers.
> Update OCM integration URL helper

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/create/machinepool/cmd.go
- pkg/arguments/interactive.go
- pkg/provider/machine_types.go
Improved shell completion — can now complete some flag values based on results from server --provider, --region, --version, --flavour, --compute-machine-type.
In some shells (fish, zsh) can show extra info for the completions :sparkles:.  In --interactive mode the descriptions are not used (not currently supported by `survey` library).
[![asciicast](https://asciinema.org/a/r6ZSapnhpBP0k8CGR2alDwwso.svg)](https://asciinema.org/a/r6ZSapnhpBP0k8CGR2alDwwso)
> Dynamic completion of flag values --region= etc.

- pkg/arguments/interactive.go
In #205, I broke the error message when passing e.g. `--region=foo` to look silly:
Error: A valid --region must be specified.
Valid options: [{Value:ap-northeast-1 Description:Asia Pacific, Tokyo} {Value:ap-northeast-2 Description:Asia Pacific, Seoul} {Value:ap-south-1 Description:Asia Pacific, Mumbai} {Value:ap-southeast-1 Description:Asia Pacific, Singapore} {Value:ap-southeast-2 Description:Asia Pacific, Sydney} {Value:ca-central-1 Description:Canada, Central} {Value:eu-central-1 Description:EU, Frankfurt} {Value:eu-north-1 Description:EU, Stockholm} {Value:eu-west-1 Description:EU, Ireland} {Value:eu-west-2 Description:EU, London} {Value:eu-west-3 Description:EU, Paris} {Value:me-south-1 Description:Middle East, Bahrain} {Value:sa-east-1 Description:South America, São Paulo} …
> Fix CheckOneOf() error message

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
There should be defaults for min/max replicas only for interactive mode.
Otherwise, they are required when --enable-autoscaling is set.
Related: https://issues.redhat.com/browse/SDA-3702
> Fix create cluster command with autoscaling

- cmd/ocm/edit/machinepool/cmd.go
- pkg/cluster/cluster.go
This bug was caused because we use the same func to create and update the nodes builder for a cluster.
It would only update if computes nodes != 0 (which means it was set by the user).
However, the default for edit additional machine pool is -1, because 0 is a valid value.
Since we now use the same `edit machinepool` command for default and additional,
I changed the check to `if computeNodes > 0` which captures both cases.
Related: https://issues.redhat.com/browse/SDA-3709
This also includes a documentation fix for --replicas flag.
Related: https://issues.redhat.com/browse/SDA-3710
> Fix empty edit default machine pool

- cmd/ocm/tunnel/cmd.go
This is to resolve private cluster urls that stopped being resolved after a `dnf upgrade` for fedora33 users.
> add --dns flag to sshuttle

- cmd/ocm/hibernate/cluster/cmd.go
- cmd/ocm/hibernate/cmd.go
- cmd/ocm/main.go
- cmd/ocm/resume/cluster/cmd.go
- cmd/ocm/resume/cmd.go
cc: @igoihman  @jhernand @cben 
Example usage: 
```
// Hibernate a cluster
ocm hibernate cluster <cluster-id>
// Resume a cluster
ocm resume cluster <cluster-id>
```
> Add support for hibernate/resume cluster

- pkg/config/config.go
This patch changes the `ocm` tool so that it explicitly sets the
`User-Agent` header with a value like `OCM-CLI/0.1.47`. This will make
it easier to identify the requests in the logs of the server.
> Set user agent

- cmd/ocm/tunnel/cmd.go
In the current tunnel implementation, tunnel will redirect traffic for the whole subnet of MachineCIDR, ServiceCIDR and PodCIDR. The subnet range is too large, and if the user want to tunnel to multiple clusters, the CIDR has a large chance to conflict.
For SRE, usually we need to tunnel to a target cluster for simple troubleshoot, and having tunnel to API server & console should be enough. Hence, adding a flag --host-only to only tunnel to apiserver & console IPs. 
```
$ ocm tunnel <cluster-name> 
$ ocm tunnel --host-only <cluster-name>
```
PS. I know `host-only` is a bad name. Let me know if you got a better name.
> Add switch for tunnel to use in-continuous IPs

- cmd/ocm/tunnel/cmd.go
The flag also can be used as "ocm tunnel ID -- --dns" if needed, so no need to re-define it.
Also, no need to use the cluster-side resolution as the addresses are public.
> remove: revert #244 as we have ocm tunnel -- --dns

- cmd/ocm/list/cluster/cmd.go
- pkg/arguments/arguments.go
Currently when the `--parameter search="..."` flag is used in the `list clusters` command the result is that two `search` query parameters are sent to the server, one containing the value given by the `--parameter` flag and another containing the search query calculated from the rest of the flags. For example, the following command:
```
$ ocm list clusters --managed --parameter search="state is 'ready'"
```
Results in a URL like this:
```
https://api.openshift.com/foo/bar?search=managed+%27t%27&search=state+is+%27ready%27
```
When the server receive that it will just ignore one of the values, so the result will not the expected combination of both search criteria.
To address that this patch changes the `list clusters` command so that it will explicitly combine the search query calculated …
> Merge search parameter into search query for `list clusters`

- pkg/cluster/describe.go
This adds the PrivateLink descriptor to the `describe cluster` command.
Card: OSD-7343
Example:
```
$ ./ocm describe cluster 1kqafv545aqi0ig05qefh6t334dgbuee
ID:            1kqafv545aqi0ig05qefh6t334dgbuee
External ID:   cb49454b-0f95-49fb-85a2-327899d5e7aa
Name:          drow-pl-01
State:         ready
API URL:       https://api.drow-pl-01.htno.p1.openshiftapps.com:6443
API Listening: internal
Console URL:   https://console-openshift-console.apps.drow-pl-01.htno.p1.openshiftapps.com
Masters:       3
Infra:         2
Computes:      2
Product:       rosa
Provider:      aws
Version:       4.7.9
Region:        us-east-1
Multi-az:      false
CCS:           true
PrivateLink:   true
Channel Group: stable
Cluster Admin: true
Organization:  Red Hat OpenShift Online
Creator: …
```
> Add PrivateLink To Describe Cluster

- cmd/ocm/post/cmd.go
The header flags are stored in args.header, not in args.parameter
> ocm post: pass correct info to ApplyHeaderFlag()

- CHANGES.adoc
- pkg/info/info.go
The most relevant changes:
- Update ocm-sdk-go to 0.1.186
- Use `less` to page cluster list
- Added ccs_only to cloud regions
- Honor machine_types ccs_only field
- ocm post: pass correct info to ApplyHeaderFlag()
- Add option to encrypt etcd during cluster installation
- list versions by channel group
- Modify resource_name comparison when populating add-ons
- Add PrivateLink To Describe Cluster
> Release 0.1.52

- CHANGES.adoc
- pkg/info/info.go
The only change in this release is the removal of the paging feature that was
introduced in the previous release. Users have complained that it disrupts
their workflows. In particular the fact that _less_ clears the screen after
finishing when the results fit in one page.
Note that in version of less included in many _Linux_ operating systems can be
configured to disable this screen clearing adding the `-F` option to the `LESS`
environment variable:
```
export LESS="-F"
```
But apparently other operating systems, in particular _macOS_, don't have this
version or less, or have a version that doesn't support that option or
environment variable.
This feature will be reintroduced later with a mechanism to persistently enable
or disable it.
Related: https://issues.redhat.com/browse/SDA-4280
> Release 0.1.53

- go.mod
- go.sum
The main reason for this update is to fix a bug in the handling of
authentication using client credentials (the `--client-id` and
`--client-secret` options). Depending on the configuration of those
client credentials the SSO server may not return a refresh token, which
the SDK expects.
Related: https://issues.redhat.com/browse/SDA-4352
Related: https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3
Related: https://github.com/openshift-online/ocm-sdk-go/pull/400
Related: https://github.com/openshift-online/ocm-sdk-go/pull/402
> Update to SDK 0.1.190

- CHANGES.adoc
- pkg/info/info.go
- Update to OCM SDK 0.1.190.
- Don't require refresh token for client credentials grant.
- Don't use refresh token if have client credentials.
> Release 0.1.54

- Makefile
- tests/main_test.go
- tests/token_test.go
- tests/version_test.go
This patch adds a `tests` directory containing tests that verify that
the `ocm` commands works as expected.
> Add CLI tests

- cmd/ocm/account/orgs/cmd.go
- cmd/ocm/account/quota/cmd.go
- cmd/ocm/account/roles/cmd.go
- cmd/ocm/account/status/cmd.go
- cmd/ocm/account/users/cmd.go
- cmd/ocm/config/get/get.go
- cmd/ocm/config/set/set.go
- cmd/ocm/get/cmd.go
- cmd/ocm/logout/cmd.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/main_test.go
- pkg/ocm/connection.go
- tests/get_test.go
- tests/logout_test.go
- tests/token_test.go
Currently the `ocm logout` command removes the `$HOME/.ocm.json`
configuration file.  his makes it difficult to have settings that
aren't related to authentication. For example, we want to introduce a
setting to enable/disable paging, and we would like to have that
persisted in the configuration file so that the user doesn't need to
change it after each logout. To allow that this patch changes the
`logout` command so that instead of removing the configuration file it
removes all the login related settings.
> Don't remove config file on logout

- cmd/ocm/config/get/get.go
- cmd/ocm/config/set/set.go
- pkg/config/config.go
- tests/logout_test.go
This patch adds a new `pager` configuration setting that will be used in
the future to configure the command to use to display output page by
page.
> Add `pager` configuration setting

- cmd/ocm/list/cluster/cmd.go
- pkg/config/config.go
- pkg/ocm/connection.go
- pkg/output/printer.go
- pkg/table/table.go
- tests/list_clusters_test.go
- tests/main_test.go
This patch changes the `list clusters` command so that it uses the
a pager command (if available) to display the results page by page.
This will not be enabled by default. To enable it set the `pager` config
variable to the command that you wish to use. For example, to use the
`less` command:
```
$ ocm config set pager 'less -F'
```
Related: https://issues.redhat.com/browse/SDA-4280
> Use pager command for `list clusters`

- .gitignore
- Makefile
- cmd/ocm/list/cluster/cmd.go
- go.mod
- pkg/data/digger.go
- pkg/data/digger_test.go
- pkg/data/main_test.go
- pkg/output/main_test.go
- pkg/output/printer.go
- pkg/output/table.go
- pkg/output/table_test.go
- pkg/output/tables/clusters.yaml
- tests/list_clusters_test.go
Add table printer
This patch adds a new `output.Table` type that simplifies writing
tabular ouptut. It is created from the `output.Printer` type introduced
in a previous patch:
```go
// Create the output table:
table, err := printer.NewTable().
Name("clusters").
Columns(args.columns).
Build(ctx)
if err != nil {
return err
}
```
When a table like this is created it reads the descriptions of the
columns from the corresponding file in the `pkg/output/tables`
directory. In this case it will read the `clusters.yaml` file. That file
should contain the descriptions of the columns of that table, in
particular it should contain the preferred width of the columns. For
example:
```yaml
columns:
- name: id
header: ID
width: 32
- name: name
header: NAME
width: 28
...
- name: external_id
header: …
```
> Add table printer

- tests/list_orgs_test.go
This patch adds a simple test for the `list orgs` command.
> Add test for `list orgs`

- .gitignore
- cmd/ocm/list/org/cmd.go
- pkg/output/tables/orgs.yaml
This patch changes the `list orgs` command so that it uses a printer
table.
> Add printer table for organizations

- tests/main_test.go
- tests/plugin_list_test.go
This patch adds a simple test for the `plugin list` command.
> Add test for `plugin list`

- cmd/ocm/plugin/list/cmd.go
- pkg/config/config.go
- pkg/output/tables/plugins.yaml
- tests/plugin_list_test.go
This patch changes the `plugin list` command so that it uses a table for
displaying results.
> Add table for plugins

- cmd/ocm/account/orgs/cmd.go
- cmd/ocm/list/org/cmd.go
- tests/account_orgs_test.go
This patch changes the `account orgs` command so that it uses a table to
display output.
Note that this command is currently identical to `list orgs`, it should
probably be changed or removed.
> Use table for `account orgs`

- cmd/ocm/account/orgs/cmd.go
- cmd/ocm/list/addon/cmd.go
- cmd/ocm/list/cluster/cmd.go
- cmd/ocm/list/idp/cmd.go
- cmd/ocm/list/ingress/cmd.go
- cmd/ocm/list/org/cmd.go
- cmd/ocm/plugin/list/cmd.go
- go.mod
- pkg/data/digger.go
- pkg/output/printer.go
- pkg/output/table.go
- pkg/output/table_test.go
- pkg/output/tables/endpoints.yaml
- pkg/output/tables/idps.yaml
- pkg/output/tables/ingresses.yaml
- pkg/output/tables/plugins.yaml
This patch changes the `output.Table` object so that it accumulates the
first rows of the output (one hundred by default) in order to learn how
to display the values.
Currently that learning is very basic: it adjusts the width of the
columns to not waste space, and only does it for columsn that don't have
a width explicitly defined in the corresponding YAML file.
This works well usually, but may product wrong results if the data in
the first one hundred rows is very different from the data in the
following rows.
> Add column width learning

- cmd/ocm/cluster/login/login.go
- cmd/ocm/create/idp/cmd.go
- cmd/ocm/create/ingress/cmd.go
- cmd/ocm/create/machinepool/cmd.go
- cmd/ocm/create/upgradepolicy/cmd.go
- cmd/ocm/create/user/cmd.go
- cmd/ocm/delete/idp/cmd.go
- cmd/ocm/delete/ingress/cmd.go
- cmd/ocm/delete/machinepool/cmd.go
- cmd/ocm/delete/upgradepolicy/cmd.go
- cmd/ocm/delete/user/cmd.go
- cmd/ocm/describe/cluster/cmd.go
- cmd/ocm/edit/cluster/cmd.go
- cmd/ocm/edit/ingress/cmd.go
- cmd/ocm/edit/machinepool/cmd.go
- cmd/ocm/hibernate/cluster/cmd.go
- cmd/ocm/list/addon/cmd.go
- cmd/ocm/list/idp/cmd.go
- cmd/ocm/list/ingress/cmd.go
- cmd/ocm/list/machinepool/cmd.go
- cmd/ocm/list/upgradepolicy/cmd.go
- cmd/ocm/list/user/cmd.go
- cmd/ocm/resume/cluster/cmd.go
- cmd/ocm/tunnel/cmd.go
- pkg/cluster/cluster.go
- tests/describe_cluster_test.go
Use subscription API to query cluster id when cluster name or external ID provided.
More context: https://issues.redhat.com/browse/SDB-2155, https://issues.redhat.com/browse/SDB-1706
> Use subscription API to query cluster id

- go.mod
- go.sum
- pkg/config/config.go
- needed if the file is overridden with "export OCM_CONFIG=$(mktemp)"
- go.mod and go.sum updated via the `make` target
> feat(login): allow for empty OCM_CONFIG

- pkg/cluster/cluster.go
- tests/describe_cluster_test.go
This patch changes the cluster lookup logic so that that it will search
for subscriptions in `Reserved` and `Active` state, and so that it will
look in the clusters collection when there are no matching results in
the subscriptions collection.
Related: https://issues.redhat.com/browse/SDA-4458
> Fix cluster lookup

- cmd/ocm/completion/cmd.go
It's regrettable for new users that running `ocm completion` with no args dumps bash script to stdout — ideally it'd show the help and require an explicit shell type e.g. `ocm completion bash`.
I kept the shell type optional to not break "existing users", but does that matter to anyone?
> Clarify `ocm completion` help

- README.adoc
- cmd/ocm/login/cmd.go
The new URL already works so it's safe to merge & release this, and since users take time to upgrade the CLI, better sooner IMHO.
related to https://issues.redhat.com/browse/OSDOCS-2290
> Update login URL for upcoming move to console.redhat.com

- README.adoc
In order to build the RPM it is necessary to add the `${HOME}/go/bin`
directory to the path, as there is where `go get ...` installs the
`go-bindata` tool.
Related: https://issues.redhat.com/browse/SDA-4671
> Update the RPM build instructions

- cmd/ocm/login/cmd.go
- cmd/ocm/main.go
- pkg/urls/well_known.go
- tests/token_test.go
- tests/whoami_test.go
This patch changes the CLI so that it will write the following message
when an operation fails because the offline access token is no longer
valid:
```
Offline access token is no longer valid. Go to
https://console.redhat.com/openshift/token to get a new
one and then use the 'ocm login --token=...' command to
log in with that new token.
```
Related: https://issues.redhat.com/browse/SDA-4686
> User friendly message when offline token is no longer valid

- CHANGES.adoc
- README.adoc
- pkg/info/info.go
- Use standard XDG configuration path for `ocm.json`
- User friendly message when offline token is no longer valid.
> Release 0.1.56

- cmd/ocm/get/cmd.go
- go.mod
- go.sum
- pkg/arguments/arguments.go
- pkg/dump/dump.go
- pkg/output/terminal.go
- tests/get_test.go
This patch changes the tool so that it doesn't rely on the `jq` tool in
order to produce color output.
The main reason to do this is to prevent incorrect handling of long
integers.
Related: https://github.com/openshift-online/ocm-cli/issues/295
> Don't use `jq` for color output

- CHANGES.adoc
- pkg/info/info.go
- Replace `go-bindata` with Go 1.16 `embed.FS`. This has no practical
implication for users, but for developers it means that the project requires
Go 1.16.
- Run tests using _GitHub_ actions instead of _Jenkins_. This increases the
platform coverate as tests now run in _Linux_, _MacOS_ and _Windows_.
- Color output is now generated internally without requiring the installation
of the `jq` tool.
- Show provisioning error code and message.
> Release 0.1.57

- README.adoc
This patch updates the RPM build spec so that it explicitly downloads
and installs Go instead of using the packages provided by the
distribution. This is currently necessary because CentOS and RHEL still
have Go 1.15 and we need at least 1.16.
> Update RPM build spec

- .github/workflows/publish-release.yaml
The action that publishes releases was uploading artifacts using the
`--data` option of the `curl` tool. That results in processing them as
ASCII and limits the size to approximately 4 MiB. The end result is that
the uploaded binaries don't work. This patch fixes that using the
`--data-binary` option instead.
Related: https://github.com/openshift-online/ocm-cli/issues/319
> Fix publish release action

- .github/workflows/publish-release.yaml
Since the introduction of the `publish-release` action the `.sha256`
files contain incorrect file names. For example, the name of the actual
released binary for Linux and x86_64 is `ocm-linux-amd64` but the file
name inside the `.sha256` file is just `ocm`. This patch fixes that
issue.
Related: https://github.com/openshift-online/ocm-cli/issues/322
> Fix binary names inside `.sha256` files

- cmd/ocm/create/user/cmd.go
Change the **cmd.go** file of the ``create user`` command to return exit
code 1 when user creating is failed with an existing username.
After the changes will be merged:
- When creating a user is failed the exit code will be 1.
- When creating multiple users, if one failed the exit status code
will be 1.
Solve Bug: SDA-4804
> Fix bug - return exit code 1 when user creating is failed

- .github/workflows/publish-release.yaml
The binary generated by `make` is `ocm.exe`, but we try to copy `ocm`.
> Fix publishing of Windows binaries

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
https://issues.redhat.com/browse/SDA-5389
> OCM-CLI should not allow additional-trust-bundle as parameter

- cmd/ocm/create/cluster/cmd.go
https://issues.redhat.com/browse/SDA-5392
> There should be readable error message when create a ccs cluster with invalid --https-proxy value

- CHANGES.md
- pkg/info/info.go
- Add STS to `describe cluster` output.
- Add BYOPC flag to `describe cluster` command.
- Support BYO-VPC cluster creation flags.
- Support cluster-wide proxy during cluster creation and update.
- Don't allow additional trust bundle as parameter.
- Add more URLs to expander.
- Readable error message when creating a CCS cluster with invalid
`--htts-proxy` value.
> Release 0.1.61

- cmd/ocm/create/cluster/cmd.go
When a user selects non-CCS or multi-AZ, we should not list regions that
are incompatible with their selection.
Refs: https://issues.redhat.com/browse/SDA-4369
> Only show relevant regions in interactive cluster create

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
https://issues.redhat.com/browse/SDA-5450
updated code to be similar to ROSA. Removed --use-existing-vpc and --cluster-wide-proxy flags.
The following are examples of valid requests and the expected results:
example 1:
./ocm create cluster vpctest20 --region us-west-1  --aws-account-id xxx --aws-access-key-id yyy --aws-secret-access-key zzz  --provider aws  -i
? CCS: Yes
? Multiple AZ: No
? OpenShift version: 4.9.18
? Compute machine type: r5.24xlarge
? Enable autoscaling: No
? Compute nodes: 2
? Install into an existing VPC (optional): Yes
? Subnet IDs (optional): subnet-0b12660243ad390a9 (us-west-1a), subnet-0a0210c16c5df930a (us-west-1a)
? Use cluster-wide proxy (optional): Yes
? HTTP Proxy (optional): http://ee.com/
? HTTPS Proxy …
> It should fail to create a cluster with proxy atrribute but no --use-existing-vpc

- CHANGES.md
- pkg/info/info.go
- Update to SDK 0.1.240
- Only show relevant regions in interactive cluster create
- Update linter config
- Add linting GH action
- Fix linting issues
- Run go mod tidy
- Unify PR actions
- ocm-cli - Improve the cluster-wide-proxy use cases
- It should fail to create a cluster with proxy atrribute but no --use-existing-vpc
- [WIP] ocm-cli should support byovpc and cluster-wide-proxy for gcp
- It should be failed when create a non-ccs cluster with proxy attributes
- Support byovpc and cluster-wide-proxy features
- GCPNetwork attributes should show in cluster describe
- Fix HTML escaping
- It should be successful to edit a ccs cluster with proxy attribute
- Update SDK to v0.1.242
> Release v0.1.62

- pkg/dump/dump.go
The library that we use to generate colored output generates ANSI
sequences that by default aren't supported by the Windows `cmd` tool.
The result is garbage. To avoid that this patch disables color output in
windows.
> Disable color in Windows

- cmd/ocm/create/idp/ldap.go
- cmd/ocm/create/idp/openid.go
I observed that the current interactive wizard for adding an IDP points to a documentation URL that doesn't redirect to IDP-specific documentation (it just lands at the OSD docs homepage).
This PR updates the links to point to the correct documentation resources.
> Correct the doc URLs for IDP creation

- CHANGES.md
- pkg/info/info.go
- Add extra scopes support for OpenID IDP
- config: Allow using encrypted refresh tokens
- Correct the doc URLs for IDP creation
- added limited support reasons to the url_expander pkg
- better error when gcp ccs creds are not provided
> Release v0.1.64

- cmd/ocm/create/cluster/cmd.go
Since the network type is defined in the API based on the OpenShift
version, we remove the client-side default. If the user overrides the
hidden flag, the API will ensure that the user has the required
capabilities to use the non-default network type for that version.
> network: Ensure there is no default network type

- cmd/ocm/create/cluster/cmd.go
> Add validation when user creates a cluster only with no-proxy (non-interacitve mode)

- cmd/ocm/edit/cluster/cmd.go
The usage instructions for `ocm edit cluster` didn't align with the actual flags, namely the `--cluster` flag. This change eliminates that flag in order to maintain consistency with `ocm {get|list|describe} cluster`.
> Swap edit cluster flags to match usage

- README.md
due to: https://go.dev/doc/go-get-install-deprecation
> docs: update the installation w/ 'go install'

- .github/workflows/publish-release.yaml
Builds the ocm CLI for darwin/arm64 (mac m1)
> Add build artifact for darwin/arm64

- .gitignore
- go.mod
- go.sum
- pkg/cluster/describe.go
- pkg/cluster/describe_test.go
When troubleshooting HyperShift clusters, sometimes it is important to inspect the relevant service cluster. This PR does this by essentially implementing:
```
❯ ocm get /api/osd_fleet_mgmt/v1/service_clusters -p search="id='$(ocm get /api/osd_fleet_mgmt/v1/management_clusters -p search="name='hs-mc-op846kea0'" | jq -r '.items[0].parent.id')'" | jq -r '.items[0].name'
hs-sc-op846kde0
```
Sample output:
```
❯ ocm describe cluster 21rrnvvf6rd4vdndl4lf3gie7mat0gna                                
ID:			21rrnvvf6rd4vdndl4lf3gie7mat0gna
External ID:		d61a016b-dd48-4f96-ac27-dc9a1b1f7b63
...
Management Cluster:     hs-mc-jsui4ri9g
Service Cluster:        hs-sc-op846kde0
```
> Return the service cluster for HyperShift clusters with `ocm describe cluster`

- CHANGES.md
- pkg/info/info.go
- docs: update the installation w/ 'go install'
- Update brew installation instructions
- Add dependabot config
- Update github actions
- Upgrade dependencies
- Bump github.com/spf13/cobra from 1.5.0 to 1.6.1
- Bump github.com/openshift-online/ocm-sdk-go from 0.1.306 to 0.1.308
- Update revocation link
- Remove validation for GCP+private clusters
- Add build artifact for darwin/arm64
- Bump k8s.io/apimachinery from 0.24.3 to 0.26.1
- Bump github.com/onsi/gomega from 1.24.2 to 1.25.0
- Bump github.com/onsi/ginkgo/v2 from 2.7.0 to 2.8.0
- Bump golang.org/x/text from 0.6.0 to 0.7.0
- Bump golang.org/x/term from 0.4.0 to 0.5.0
- Bump github.com/onsi/gomega from 1.25.0 to 1.26.0
- Bump github.com/openshift-online/ocm-sdk-go from 0.1.308 to 0.1.316
- Bump github.com/openshift/rosa from 1.2.11 …
> Release v0.1.66

- pkg/cluster/describe.go
Adds the subscription display name (the one used by the web UI) to the describe output
> Add display name to describe output

- pkg/cluster/describe.go
This is similar to the change done in [ROSA CLI](https://github.com/openshift/rosa/commit/f3065738663e9dcca26d9031a15f05f722825609) and will help the debugging.
Examples:
Normal output
```
State:			ready
```
Additional error
```
State:			error
Details:		Manifest work deletion is stuck
```
Provisioning error
```
State:			error (OCM3999 - Unknown error. Check this cluster's installation logs for more details, or delete this cluster and try again. If this issue persists, contact support.)
```
Related: OCM-2177
> OCM-2177 | Add additional status details to the describe cluster output

- CHANGES.md
- pkg/info/info.go
- Bump github.com/onsi/ginkgo/v2 from 2.8.1 to 2.9.1
- Add display name to describe output
- Bump github.com/onsi/gomega from 1.27.3 to 1.27.6
- Update linting configuration
- Add HCP status to list/describe output
- Bump k8s.io/apimachinery from 0.26.1 to 0.27.1
- Bump github.com/openshift/rosa from 1.2.15 to 1.2.17
- Bump golang.org/x/term from 0.6.0 to 0.7.0
- Bump github.com/spf13/cobra from 1.6.1 to 1.7.0
- Update _copr_ build instructions
- Bump github.com/onsi/ginkgo/v2 from 2.9.2 to 2.9.7
- Bump k8s.io/apimachinery from 0.27.1 to 0.27.2
- Bump github.com/openshift-online/ocm-sdk-go from 0.1.330 to 0.1.344
- Bump github.com/openshift/rosa from 1.2.17 to 1.2.22
- OCM-2177 | Add additional status details to the describe cluster output
> Release v0.1.67

- pkg/cluster/cluster.go
First step towards #517.
At least doesn't lie to user and gives hint how to find past data:
```
> ocm describe cluster 0e68a621-c00e-4bbf-a4bb-9915ae6cc947
Error: Can't retrieve cluster for key '0e68a621-c00e-4bbf-a4bb-9915ae6cc947': There are no subscriptions or clusters with identifier or name '0e68a621-c00e-4bbf-a4bb-9915ae6cc947'
```
```
> ocm describe cluster 0e68a621-c00e-4bbf-a4bb-9915ae6cc947
Error: Can't retrieve cluster for key '0e68a621-c00e-4bbf-a4bb-9915ae6cc947': Cluster was Deprovisioned, see `ocm get subscription 2S434jffVG4fSgDdK4cbkDTxVNp` for details``
```
This affects ALL commands that use `GetCluster` helper.
:question: Behavior change: when there is 1 active cluster and also 1+ past clusters reusing same display_name, previously the active one was silently used; now …
> improve GetCluster message when Subscription exists but is inactive

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/edit/ingress/cmd.go
Related issue: https://issues.redhat.com/browse/OCM-3061
> OCM-3061 | fix: allow to reset route selectors/excluded namespaces

- cmd/ocm/create/cluster/cmd.go
- go.mod
- go.sum
- pkg/billing/billing.go
- pkg/cluster/cluster.go
- pkg/cluster/describe.go
**Changed**
- Added subscription_type parameter to create cluster command
- Added validation to have one of the specific options for the command
- Defaulted subscription_type to standard
**Tested**
- Cluster should be created based on the subscription_type parameter passed in cli : tested
> OCM-2966 : Feat : Added subscription_type parameter to create cluster command

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/interactive.go
**Changed**
- Fetched default values from flavour endpoint
- Set the values for CIDRs and host prefix
**Tested**
- CIDR and host prefix should have the default values auto populated in case of no other input : tested
> OCM-3801 | Feat | Added default values for CIDRs and host prefix

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/list/version/cmd.go
- pkg/cluster/versions.go
**Changed**
- Added gcpMarketplaceEnabled flag for filtering out supported versions of OCM CLI
**Tested**
- Only supported versions should be visible for gcp marketplace clusters : tested
> OCM 3768 | Feat | Filtered OCM versions for marketplace gcp clusters

- CHANGES.md
- pkg/info/info.go
-447488d Added default values for CIDRs and host prefix -672ca8b Fixed CIDR order and added back the comment -fbff80f Fixed the comment statement
-1f2b39b fix duplicate machine pool information printed for the same cluster -f0fadd8 add tests for list machinepools command
-5b60bbf added failure tests for list machinepools command -498c54e Filtered OCM versions for marketplace gcp clusters -a9f32b7 Changed string pointer to string and removed nil check -0aca318 Changed gcp-marketplace keyword to marketplace-gcp
> Release v0.1.69

- cmd/ocm/create/cluster/cmd.go
**Changed**
- Added terms and conditions flag for GCP
- Added check to confirm the flag is set to true for both interactive and non-interactive mode
**Tested**
- Interactive/Non-interactive mode should create clusters only after the flag is set to true
> OCM 3993 | Feat | Add GCP marketplace terms and conditions for marketplace GCP clusters

- cmd/ocm/create/cluster/cmd.go
**Changed**
- Changed marketplace-gcp-terms error message for non-interactive mode
**Tested**
- Non-interactive mode should throw an error `"Error: Review and accept Google Terms and Agreements on https://console.cloud.google.com/marketplace/agreements/redhat-marketplace/red-hat-openshift-dedicated. Set the flag --marketplace-gcp-terms to true once agreed in order to proceed further."` : tested
> OCM-4186 | Feat | Changed marketplace-gcp-terms error message for non-interactive mode

- pkg/arguments/interactive.go
**Changed**
- Convert relative path containing tilde for service account file
**Tested**
- Path containing tilde should be valid for service account file
> OCM-4184 | Feat | Convert relative path containing tilde for service account file

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
Issue: https://issues.redhat.com/browse/OCM-4465
Adds `--vpc-project-id` flag to specify host project id when creating a shared-vpc GCP cluster. 
In the interactive flow, if the user selects yes to `Install into an existing VPC` they will get a follow-up prompt `Install into a shared VPC`, which defaults to No.
```
? Install into an existing VPC (optional): Yes
? vpc name: <vpc-name>
? control plane subnet: <subnet-name>
? compute subnet: <subnet-name>
? Install into a shared VPC (optional): Yes
? Vpc project id: <project-name>
```
In the existing flow when `use-existing-vpc` is true the cli will run client-side validation that the vpc and subnets exist. If using shared vpc this validation will be skipped (because it can't be verified with existing credentials).
> Add vpc-project-id flag for shared VPC on GCP

- pkg/cluster/describe.go
> OCM-5131 | fix: don't show additional compute SGs describing cluster

- CHANGES.md
- pkg/info/info.go
- OCM-4960: Do not print expiration timestamp if not set
- OCM-5131 | feat: add SG IDs to describe cluster and list machinepools
- Add 'secure-boot-for-shielded-vms' flag to expose secureboot on GCP
- OCM-5131 | fix: don't show additional compute SGs describing cluster
> Release v0.1.72

- cmd/ocm/create/cluster/cmd.go
- pkg/cluster/describe.go
Demo:
```
[rcampos@rcampos-thinkpadt14sgen2i ocm-cli]$ ./ocm create cluster -i
? cluster name rc-test
? Subscription type: standard (Annual: Fixed capacity subscription from Red Hat)
? Cloud provider: gcp
? CCS: Yes
? Service account file: REDACTED
? Multiple AZ: No
? Secure boot support for Shielded VMs: No
? Region: us-east4
? OpenShift version: 4.14.6
? Compute machine type: custom-4-16384
? Enable autoscaling: No
? Compute nodes: 2
? Install into an existing VPC (optional): No
? Machine CIDR: 10.0.0.0/16
? Service CIDR: 172.30.0.0/16
? Pod CIDR: 10.128.0.0/14
? Host prefix: 23
? Private cluster (optional): No
ID:                     REDACTED
External ID:
Name:                   rc-test
Display Name:           rc-test
State:                  validating
API URL:
API Listening: …
```
> OCM-4783 | feat: display warnings after cluster creation

- cmd/ocm/create/idp/cmd.go
- cmd/ocm/create/idp/google.go
Updated the usage string in cmd.go as well
Resolves #595
> Use Hostname() to set --hosted-domain

- pkg/cluster/describe.go
Issue: https://issues.redhat.com/browse/OCM-2853
Hide AWS-specific fields from GCP cluster describe and vice versa.
AWS-specific features:
- Private Link
- STS
GCP-specific features:
- Secure boot
- BYOVPC fields
> Display only platform-relevant field in cluster describe

- pkg/cluster/describe.go
Adds a link to describe cluster, to the cluster history as displayed in OCM
> Display a cluster history URL in cluster describe

- cmd/ocm/list/rhRegion/cmd.go
- cmd/ocm/login/cmd.go
- pkg/urls/main_test.go
- pkg/urls/url_expander_test.go
- pkg/urls/well_known.go
- pkg/urls/well_known_test.go
This MR tweaks the `ocm login --url` resolution algorithm to try to reuse `cfg.URL` before falling back to "api.openshift.com". New `--url` resolution algorithm (from highest priority to lowest priority):
1. runtime `--url` cli arg (key found in `urlAliases`)
2. runtime `--url` cli arg (non-empty string)
3. [NEW] config file `URL` value (non-empty string)
4. sdk.DefaultURL
I also improved the recently added `ocm list rh-region` to be a bit more helpful:
* show discovery URL used
* add optional `--discovery-url` flag with the same url resolution behavior as `ocm login`
* tabular formatting
* display region name and its associated url rather than just region name
> OCM-3226 | feat: improving ocm login and ocm list rh-region url resolution

- cmd/ocm/edit/cluster/cmd.go
ocm edit will update always the cluster even there is no new configuration. This commit checks the configuration before make the update call.
> OCM-6450 | No update cluster with empty config

- pkg/output/table_test.go
- pkg/output/tables/clusters.yaml
This follows up on https://github.com/openshift-online/ocm-cli/pull/605
> OCM-6140: make name width to be 54 chars to fix truncation issue in case of longer name > 28 chars

- cmd/ocm/edit/cluster/cmd.go
This commit adds a parameter when creating the command that check for a minimum amount of arguments. The
command will fail if no parameters are used.
> OCM-6407 | edit option sends an empty payload

- cmd/ocm/edit/ingress/cmd.go
- cmd/ocm/edit/ingress/cmd_test.go
- cmd/ocm/edit/ingress/main_test.go
- go.mod
- go.sum
- pkg/utils/main_test.go
- pkg/utils/slices.go
- pkg/utils/slices_test.go
- pkg/utils/strings.go
- pkg/utils/strings_test.go
> OCM-6030 | feat: allow to edit component routes of ingress

- CHANGES.md
- pkg/info/info.go
- 165b90e OCM-4783 | feat: display warnings after cluster creation
- 0973f7b Display a cluster history URL in cluster describe
- ad98440 Fix minor formatting issue with cluster describe
- ea1c988 OCM-4962 | Feat | Add OAuth login using PKCE (#590)
- 98944f7 OCM-5759 | feat: Add Device Code Flow (#591)
- ff1c142 Display only platform-relevant field in cluster describe
- fab7ccf OCM-5281 | Feat | Add region validation from ocm-shards and list regions command (#586)
- f279dc7 Use Hostname() to set --hosted-domain
- d0f8459 improving ocm login and ocm list rh-region url resolution to reuse the url saved in config before falling back to api.openshift.com
- d894c2a OCM-6407 | edit option sends an empty payload
- 9cf11ef OCM-6450 | No update cluster with empty config
- 1caf2d0 OCM-5941 | add …
> Release v0.1.73

- cmd/ocm/account/quota/cmd.go
- cmd/ocm/account/roles/cmd.go
- cmd/ocm/account/status/cmd.go
- cmd/ocm/account/users/cmd.go
- cmd/ocm/get/cmd.go
- cmd/ocm/login/cmd.go
- pkg/ocm/connection.go
- pkg/properties/properties.go
Adds the ability to change the OCM API URL based on the environment variable `OCM_URL` allowing a user to change the OCM context without changing global state on their machine.
Satisfies OCM-8459.
To test this, I built the binary locally and ran a few commands, expecting different output.
* ./ocm list clusters --parameter search="name like 'hs-mc%'"
* OCM_URL=https://api.[regional-api].openshift.com ./ocm list clusters
> Adds ability to change api url via env var

- CHANGES.md
- pkg/info/info.go
- 3423d52 OCM-1888: Add docs for ocm delete account subcommands and arguments
- 42a6c63 OCM-4965: Keyring configuration storage (#600)
- 01c0241 OCM-6528 | feat: add describe ingress cmd
- debb035 OCM-8013| feat: Dockerfile for Konflux builds
- 79d7322 konflux-tekton build pipelines
- e79a4bf Red Hat Konflux update ocm-cli
- 5ea7344 Trigger pipeline only if event title starts with Konflux
- edd560c Bump ocm-sdk-go to v0.1.422 (#620)
- 5e4c99b Adds ability to change api url via env var (#621)
- 2a1f92e OCM-1398: support 'user' as variable for ocm config
- a248a57 Update Konflux references (#617)
- 8448029 Update Konflux references to fa168cd (#623)
- 441189f Red Hat Konflux purge ocm-cli (#624)
> Release v0.1.74

- hack/build_release_images.sh
before building release images , check and fail if unable to determine release version
> Check for Release Version

- cmd/ocm/create/cluster/cmd.go
- go.mod
- go.sum
- pkg/cluster/cluster.go
- pkg/provider/wif_configs.go
Issue: https://issues.redhat.com/browse/OCM-8008
- Adds --wif-config flag for cluster create
- Adds interactive prompt following CCS for authentication method
**Interactive view (select auth type):**
```
? CCS: Yes
? Method of authenticating GCP cluster
? Authentication method:  [Use arrows to move, type to filter]
> Workload Identity Federation (WIF)
Service account
```
**Interactive view (select WIF config to use):**
```
? CCS: Yes
? Authentication method: Workload Identity Federation (WIF)
? Specifies the GCP Workload Identity Federation config used to authenticate.
? WIF Configuration:  [Use arrows to move, type to filter]
> jdg01 (2crdj6l18l0uqfoqq4873a4alp0t9v4r)
```
**Create cluster help view:**
```
Usage:
ocm create cluster [flags] NAME
Flags:
--wif-config string …
```
> Add wif config cluster create option

- cmd/ocm/gcp/create-wif-config.go
- go.mod
- go.sum
Issue: https://issues.redhat.com/browse/OCM-10035
Project number is a required field for creating a wif config that can be determined from the project id using a gcp client
> Set project number on wif config creation

- cmd/ocm/gcp/get-wif-config.go
Related issue: https://issues.redhat.com/browse/OCM-9946
> Support listing and parameters in 'gcp get wif-config'

- CHANGES.md
- pkg/info/info.go
-416843e OSD-24332 Adding CNI Type to the printed output. -ca71863 Introduce gcp WIF sub-commands to manage wif-configs (#619) -5f9697b multi arch release images (#631)
-951d7cd Red Hat Konflux update ocm-cli (#633)
-2604647 Limit Konflux Pipeline Runs (#634)
-9645301 Update Konflux references (#635)
-c797dfb Update Konflux references to 0dc3087
-28b521d support hermetic build (#636)
-3117d6b Update Konflux references to 9eee3cf
-d228140 Update Konflux references to 71270c3
-0ff233b update konflux pipeline (#641)
-ae2093b Update Konflux references
-2ae4aa0 Update Konflux references
-bdd172b Update Konflux references to f93024e
-d750acc Red Hat Konflux update ocm-cli Signed-off-by: red-hat-konflux <konflux@no-reply.konflux-ci.dev>
-0bbcf6e Update Konflux references
-21ff6b8 Replace wif …
> Release v0.1.75

- cmd/ocm/create/cluster/cmd.go
- pkg/provider/wif_configs.go
Related issue: https://issues.redhat.com/browse/OCM-10207
Only display options for wif configs that are not used by any existing clusters.
Also accept wif config ID or name when assigning value to `--wif-config` flag
> OCM-10207 | Filter wif configs in interactive mode

- cmd/ocm/gcp/delete-wif-config.go
- cmd/ocm/gcp/list-wif-config.go
- pkg/output/tables/wifconfigs.yaml
Issue: [OCM-11561](https://issues.redhat.com/browse/OCM-11561)
Dry-run the delete to verify the wif-config can be deleted so the WIF resources aren't destroyed while in use.
> Dry-run wif config delete before tearing down cloud resources

- cmd/ocm/create/cluster/cmd.go
- go.mod
- go.sum
- pkg/cluster/cluster.go
Ref: https://issues.redhat.com/browse/OCM-11842
> OCM-11842 | feat: Updates to support GCP-PSC clusters

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/delete-wif-config.go
- cmd/ocm/gcp/gcp.go
- cmd/ocm/gcp/helpers.go
- cmd/ocm/gcp/update-wif-config.go
Issue: https://issues.redhat.com/browse/OCM-11690
`--mode` flag replaces `--dry-run` where:
&nbsp;&nbsp;&nbsp;&nbsp;`mode=auto` is the default and runs all the necessary actions
&nbsp;&nbsp;&nbsp;&nbsp;`mode=manual` can be set and outputs commands to a script to be run manuallly
```
Create workload identity configuration
Usage:
ocm gcp create wif-config [flags]
Flags:
-h, --help                 help for wif-config
-m, --mode string          How to perform the operation. Valid options are:
auto (default): Resource changes will be automatic applied using the current GCP account
manual: Commands necessary to modify GCP resources will be output to be run manually (default "auto")
--name string          User-defined name for all created Google cloud resources
--output-dir string    Directory …
```
> Replace wif dry-run flag with mode

- CHANGES.md
- pkg/info/info.go
-e034b6b Update Konflux references to 2418e94
-5066ea0 Filter wif configs in interactive mode (#660) -878f5e3 Initial refactor to prepare to move the connection builder and config packages to ocm-common -1ea2e05 lint
-2c66dc0 removes redundant api url
-65bf8cf Add role prefix flag on create wif-config (#662) -a39ce2e Grant access to support group during WifConfig creation (#663) -0275d67 Revert "Grant access to support group during WifConfig creation (#663)" (#664) -7cddc94 Wif creation improvements, including logic to grant support access as part of wif creation. (#666) -7f41626 Update Konflux references
-b9a750c UpdatesToKonflux (#668)
-e4aa770 OCM-10615 | Implement 'gcp wif-config update' command (#667) -cf6e500 Dry-run wif config delete before tearing down cloud resources (#670) …
> Release v0.1.76

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/gcp.go
Tests:
```
[rcampos@rcampos-thinkpadt14sgen2i ocm-cli]$ ./ocm gcp create wif-config 
Error: flag 'name' is required
[rcampos@rcampos-thinkpadt14sgen2i ocm-cli]$ ./ocm gcp create wif-config --name rc-test
Error: Flag 'project' is required
[rcampos@rcampos-thinkpadt14sgen2i ocm-cli]$ ./ocm gcp create wif-config --name rc-test --project sda-ccs-1
2024/10/15 16:43:51 Creating workload identity configuration...
```
```
[rcampos@rcampos-thinkpadt14sgen2i ocm-cli]$ ./ocm gcp create wif-config --interactive
? WifConfig name rc-test
? Gcp Project ID sda-ccs-1
2024/10/15 16:44:15 Creating workload identity configuration...
```
> adding interactive mode for WifConfig creation

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
Issue: https://issues.redhat.com/browse/OCM-11703
Require provider, do not default to AWS, and check for provider-specific flags
> OCM-11703 | Update provider flag check 

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
Issue: https://issues.redhat.com/browse/OCM-11699
- Require gcp authentication method be clear based on input
- Address issue where no means of authentication (or two conflicting options) are provided in non-interactive mode
- Cover invalid scenarios where authentication method is set in non-ccs mode
```
ocm create cluster --ccs --provider=gcp --dry-run=true jjjj
Error: either wif-config or GCP service account file must be specified
ocm create cluster --ccs --provider=gcp --dry-run=true jjjj --wif-config=test --service-account-file=key.json
Error: can't use both wif-config and GCP service account file at the same time
```
> Do not default GCP authentication type

- cmd/ocm/create/cluster/cmd.go
https://issues.redhat.com/browse/OCM-11842
1. Make the interactive workflow for ClusterPrivacy/ BYO- VPC  similar to UI
2. For WIF clusters, Ensure  PSC is set when Cluster is Private
> OCM-11842 : Improve gcp cluster creation with psc -UX

- pkg/cluster/describe.go
[OCM-11842](https://issues.redhat.com/browse/OCM-11842)
Adding PSC and XPN config paramaters to the cluster description
> OCM-11842 | Add PSC-XPN to cluster  description

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/delete-wif-config.go
- cmd/ocm/gcp/flag_descriptions.go
- cmd/ocm/gcp/gcp.go
- cmd/ocm/gcp/get-wif-config.go
- cmd/ocm/gcp/list-wif-config.go
- cmd/ocm/gcp/update-wif-config.go
- pkg/arguments/arguments.go
The commands for cluster creation and management of wif-config resources were reviewed and made consistent in order to provide the user with a uniform experience.
The attached zip file contains text files with the help messages of these commands. Also included are screen recordings of running commands in interactive mode.
[ocm_cli_ux.zip](https://github.com/user-attachments/files/17500790/ocm_cli_ux.zip)
> OCM-10728 | interface improvements

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/gcp-client-shim.go
- cmd/ocm/gcp/scripting.go
Issue: https://issues.redhat.com/browse/OCM-10448
Descriptions are set on the following resources while applying WIF
- Workload Identity Pool
- Workload Identity Pool provider
- Service Accounts
- Custom IAM Roles
For wif-config resources the description is
> Created by the OCM CLI for WIF config {displayName}
For roles, which aren't specific to a wif-config, it is
> Created by the OCM CLI for Workload Identity Federation on OpenShift
> Add more descriptions to WIF resources

- hack/build_release_images.sh
I missed the shasum file in the MR earlier today
https://github.com/openshift-online/ocm-cli/pull/687
> remove version from release image filenames

- CHANGES.md
- pkg/info/info.go
Version update is to align and sync  with Konflux Release pipeline that will publish the cli executable to RH content-gateway.
-8b70707 Release v0.1.76 (#674)
-2ef1e1d Update Konflux references to 67f0290 (#676) -c63247f Show all WIF configs in interactive dropdown (#677) -f1d29bc adding interactive move for WifConfig creation (#675) -1382a6c Require provider, do not default to AWS, and check for provider-specific flags (#678) -d0b58b4 Do not default GCP authentication type (#679) -db35759 improve psc cli UX (#681)
-862b072 OCM-11993 | Describe cluster shows WifConfig data (#683) -4053505 Add PSC-XPN to cluster  description (#685) -0c456f8 OCM-10728 | interface improvements (#686) -1e27ded Add more descriptions to WIF resources (#684) -cdf6466 update filenames in konflux release …
> Release v1.0.2

- cmd/ocm/gcp/gcp.go
- cmd/ocm/gcp/verify-wif-config.go
- go.mod
- go.sum
Issue: https://issues.redhat.com/browse/OCM-12286
```bash
➜  ocm gcp verify wif-config -h
Verify a workload identity federation configuration (wif-config) object.
Usage:
ocm gcp verify wif-config [ID|Name] [flags]
Flags:
-h, --help   help for wif-config
➜  ocm gcp list wif-configs                                                           
ID                                DISPLAY NAME  PROJECT ID
2fdn79v1eg7btv5qlakanc4sq8917ut6  jdg           sda-ccs-1 
➜  ocm gcp verify wif-config jdg
WIF configuration is valid
➜  ocm gcp verify wif-config jdg
Error: verification failed with error: missing role 'compute.storageAdmin'
Running 'ocm gcp update wif-config' may fix errors related to cloud resource misconfiguration.
exit status 1
➜  ocm gcp update wif-config jdg
➜  ocm gcp verify wif-config …
```
> Add command 'gcp verify wif-config'

- docker/Dockerfile
- hack/build_release_images.sh
Ref : https://issues.redhat.com/browse/OCM-12467
- Removing the checksum file which is no longer  needed as Konflux creates and adds its own
- copying the binaries to /usr/local/bin as required by the binaries-release-pipeline
> OCM-12467 | feat : Updates for binaries-release-pipeline

- cmd/ocm/gcp/gcp-client-shim.go
- pkg/gcp/client.go
- pkg/gcp/error_handlers.go
- pkg/gcp/helpers.go
**Overview**
The following new behavior was added to the functionality of the command used to update resources associated with wif-configs:
- re-enable disabled service accounts
- re-enable disabled custom roles
- re-enable disabled workload identity pool
- overwrite identity provider misconfigurations
**Testing**
The resources of a test wif-config resource was manually modified into the states described above. Running `ocm gcp verify wif-config` confirmed that the error related to the misconfiguration was detected. After running `ocm gcp update wif-config`, verification succeeds. Manual inspection of GCP resources confirms that their configuration was corrected through calling the update command.
> OCM-12971 | 'ocm gcp update wif-config' remediates all wif-config misconfigurations

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/flag_descriptions.go
- cmd/ocm/gcp/gcp.go
- cmd/ocm/gcp/helpers.go
- cmd/ocm/gcp/update-wif-config.go
- go.mod
- go.sum
Version flag expects a string representing an Openshift minor release in the form 'X.Y'. On create this sets the wif template used by the wif config. On upgrade, the version is added to the list of templates.
Given a version like `4.17`, the CLI will parse that it is in `X.Y` form and convert it to the expected wif template id form `v4.17`. Otherwise it will pass the input directly for the backend to validate.
Example use:
```
➜  ocm-cli git:(OCM-12391) ✗ go run ./cmd/ocm gcp create wif-config --name=jdg3 --project=sda-ccs-1 --version=4.17 --mode=manual
```
The flag can also be set during interactive create mode:
```
➜  ocm-cli git:(OCM-12391) ✗ go run ./cmd/ocm gcp create wif-config --mode=manual -i
? wif-config name: name
? Gcp Project ID: sda-ccs-1
? The OCP version to configure the …
```
> OCM-12391 | feat: Add 'version' flag to wif-config create and update commands

- cmd/ocm/gcp/verify-wif-config.go
The update command takes care of all detectable verification errors. The help message will be updated to reflect this.
> updated help message for wif verification errors

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/gcp-client-shim.go
- go.mod
- go.sum
- pkg/gcp/client.go
- pkg/gcp/error_handlers.go
- pkg/gcp/policy.go
- pkg/utils/jwks.go
- pkg/utils/jwks_test.go
The included changes provide the following properties to the update command: 
* Operations that modify GCP cloud resources are always accompanied by a log message displayed to the user.
* Changes to GCP cloud resources are made only when necessary.
Additional logic was needed to check the configuration of jwks and service account access. Prior to this, these resources were being updated every time the command was called.
> Improved UX for updating wif-config.

- cmd/ocm/gcp/delete-wif-config.go
- cmd/ocm/gcp/gcp-client-shim.go
- cmd/ocm/gcp/gcp_client_shim_test.go
- cmd/ocm/gcp/gcp_suite_test.go
Deleted service accounts retain their project iam policy bindings. Without unbinding the service accounts that associated with wif-configs, users run the risk of hitting the GCP quota of 1,500 bindings and needing to manually delete these stale policy entries. Through the changes in this commit, service account bindings related to the wif-config being deleted will be unbound.
These changes were confirmed through a combination of unit tests and manual integration tests. The unit tests demonstrate that the logic to remove members from a binding works as expected. 
The correctness of the patch was tested as follows. The count of deleted service account bindings was first tallied. Then a wif-config resource was created. The wif-config resource was then deleted, and a new count of the number …
> OCM-14358 | unbind service accounts when deleting wif-configs

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/update-wif-config.go
- cmd/ocm/gcp/verify-wif-config.go
- pkg/utils/helper.go
The IAM API is eventually consistent. If the user created the wif-config service accounts needed for cluster deployment within too brief a period, then the backend will not yet have access to it. To avoid confusing error messages being returned, the ocm-cli will verify that the backend can see the resources before wif-config creation is considered complete.
The attached text file shows how the changes included in this patch was tested.
[ocm-14483-cli-test.txt](https://github.com/user-attachments/files/19349434/ocm-14483-cli-test.txt)
> Improving UX around gcloud iam api consistency model

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/delete-wif-config.go
- cmd/ocm/gcp/gcp-client-shim.go
- cmd/ocm/gcp/update-wif-config.go
- pkg/utils/helper.go
Because of the iam api's eventual consistency model, wif-config creation may face sporadic permission errors which disrupt the creation process. The below logs show an example of the errors which may occur as part of this issue:
```
-> ocm gcp create wif-config --name dummy-test-march4 --project sda-ccs-1
2025/03/04 10:19:24 Bound roles to principal 'group:sd-sre-platform-gcp-access@redhat.com'
2025/03/04 10:19:24 Workload identity pool created with name '2hafc91hielatppu8oftg5bgle64efts'
2025/03/04 10:19:25 Workload identity provider created with name 'oidc' for pool '2hafc91hielatppu8oftg5bgle64efts'
2025/03/04 10:19:26 IAM service account 'cloud-network-config-ctrl-efts' has been created
2025/03/04 10:19:27 Bound roles to principal …
```
> OCM-14357 | Ensuring wif commands are resilient to GCP's consistency model

- cmd/ocm/create/cluster/cmd.go
- pkg/billing/billing.go
From `ocm create cluster --help` menu:
` --subscription-type string  The subscription billing model for the cluster. Options are { standard, marketplace-gcp }. (default "standard")`
From interactive `-i`:
```
? Subscription type:  [Use arrows to move, type to filter, ? for more help]
> standard (Annual: Fixed capacity subscription from Red Hat)
marketplace-gcp (On-Demand: Flexible usage billed through the Google Cloud Marketplace)
```
From flag `--subscription-type`:
```
Error: A valid --subscription-type must be specified.
Valid options: [standard (Annual: Fixed capacity subscription from Red Hat) marketplace-gcp (On-Demand: Flexible usage billed through the Google Cloud Marketplace)]
```
> OCM-15741 | remove marketplace-rhm option from subscription-type options

- docker/Dockerfile
```
yingzhan@yingzhan-mac  ~/ying-work/code/ocm-cli   ying-test ±  podman build -f docker/Dockerfile --platform linux/amd64   -t myocm .
[1/2] STEP 1/4: FROM registry.access.redhat.com/ubi9/go-toolset:latest AS builder
[1/2] STEP 2/4: COPY . .
--> 157f776b7a99
[1/2] STEP 3/4: ENV GOFLAGS=-buildvcs=false
--> b88a4766c33d
[1/2] STEP 4/4: RUN git config --global --add safe.directory /opt/app-root/src &&     make build_release_images
bash ./hack/build_release_images.sh
go: downloading github.com/golang/glog v1.2.4
go: downloading github.com/spf13/cobra v1.7.0
go: downloading github.com/spf13/pflag v1.0.6
go: downloading cloud.google.com/go/iam v1.1.8
go: downloading github.com/AlecAivazis/survey/v2 v2.3.7
go: downloading github.com/googleapis/gax-go/v2 v2.14.1
go: downloading …
```
> OCM-15127 | Add make binary in ocm-cli image

- CHANGES.md
- pkg/info/info.go
-f95acd1 Update github.com/golang/groupcache digest to 2c02b82 -a4c0ee2 Update github.com/jackc/pgservicefile digest to 5a60cdf -2f87995 Update Konflux references (#734)
-4a1708e updates to konflux pipeline for 1.0.5 (#756) -687527d Bump github.com/openshift-online/ocm-sdk-go from 0.1.463 to 0.1.465 -de7adc6 remove marketplace-rhm option from subscription-type options (#773) -436ff34 secure-boot-for-shielded-vms flag for create machinepool (#778) -3440bb5 [OCM-15127](https://issues.redhat.com//browse/OCM-15127) | Add make binary in ocm-cli image (#779) -64ca7ac secure-boot-for-shielded-vms flag tests (#780) -822e0f2 Bump github.com/MicahParks/jwkset from 0.5.20 to 0.7.0 (#728) -8474de0 Update Konflux references
-2ecdf68 Bump github.com/spf13/cobra from 1.7.0 to 1.9.1 (#748) -ea64448 Bump …
> Release v1.0.6

- cmd/ocm/create/cluster/cmd.go
- pkg/cluster/cluster.go
From `-i`:
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create cluster -i
? Cluster name: mipereir-fips
? Subscription type: standard (Annual: Fixed capacity subscription from Red Hat)
? Cloud provider: gcp
? CCS: Yes
? Authentication type: Workload Identity Federation (WIF)
? WIF configuration: mipereir-stg (2j75tie8m8bofi0q4g338pql5isfjpuf)
? Region: us-east1
? Multiple AZ: No
? Secure boot support for Shielded VMs: No
? Use Custom KMS Keys (optional): No
? Enable FIPS cryptography: Yes
? OpenShift version:  [Use arrows to move, type to filter, ? for more help]
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create cluster -i
? Cluster name: mipereir-fips
? Subscription type: standard (Annual: Fixed capacity subscription from Red Hat)
? Cloud provider: gcp …
> OCM-9528 | Expose FIPS flag in OCM CLI when provisioning an OSD cluster on Google Cloud

- cmd/ocm/create/cluster/cmd.go
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create cluster mipereir-sub --ccs=true --provider=gcp --region=us-central1 --wif-config=mipereir-stg --subscription-type=standard
ID:	2j8cevk356vjqeuel5mpfnbimc0d16no
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create cluster mipereir-gcp --ccs=true --provider=gcp --region=us-central1 --wif-config=mipereir-stg --subscription-type=standard --dry-run
dry run: Would be successful.
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create cluster mipereir-sub --ccs=true --provider=gcp --region=us-central1 --wif-config=mipereir-stg --subscription-type=marketplace-gcp --marketplace-gcp-terms --dry-run
setting provider to gcp
setting ccs to 'true'
dry run: Would be successful. …
> OCM-16225 | Cannot set param "--subscription-type", always get error

- pkg/arguments/arguments.go
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create cluster -h | grep availability-zones
--availability-zones stringArray                        Cloud provider availability zones
> OCM-16713 | “--availability-zones” help text incorrectly implies AWS-only support
