- CHANGES.adoc
- pkg/info/info.go
- Don't print usage message when the `get`, `post`, `patch` and `delete`
commands receive error responses from the server.
> Release 0.1.21

- CHANGES.adoc
- pkg/info/info.go
- Fix quota output to look at correct API field.
> Release 0.1.24

- cmd/ocm/login/cmd.go
This patch adds aliases for well known gateway URLs. For example, it
will now be possible to login to the integration environment using the
following command:
```
ocm login --token=... --url=integration
```
> Add URL aliases

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes in this version are the following:
- Added new `cluster create` command.
- Added support for `production`, `staging` and `integration` as values
of the `--url` parameter.
> Release 0.1.25

- cmd/ocm/cluster/create/create.go
Currently the `cluster create` command retrieves only the first page of
enabled versions. This works fine in environments with less than 100
versions, but in the integration environment there are already 116
versions. This results in rejecting the command when the user tries to
use any of the newer versions that aren't in the first page. To avoid
that this patch changes the command so that it will always retrieve all
the versions, even if there are more than 100.
> Retrieve all enabled versions

- cmd/ocm/login/cmd.go
@jhernand please review.
This guides users towards using --token from https://cloud.redhat.com/openshift/token.
That page is not yet advertised in UI but I think we should, as that's the sane ways for customers to access the API?
```sh
$ ocm login
In order to log in it is mandatory to use '--token', '--user' and '--password', or '--client-id' and '--client-secret'.
You can obtain a token at: https://cloud.redhat.com/openshift/token .
See 'ocm login --help' for full help.
$ echo $?
1
```
Works with some flags too, as long as you didn't provide crendentials:
```sh
$ ocm login --url=staging
In order to log in it is mandatory to use '--token', '--user' and '--password', or '--client-id' and '--client-secret'.
You can obtain a token at: https://cloud.redhat.com/openshift/token .
See 'ocm login …
```
> Allow bare `ocm login` to suggest the token page without extra noise

- CHANGES.adoc
- pkg/info/info.go
- Add `--flavour` option to `ocm cluster create`.
> Release 0.1.30

- Makefile
- build_tag.sh
- go.mod
- go.sum
- pkg/config/config.go
The changes in this pull request add support for building the binary for Windows.
> Add support for Windows

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes in the new release are the following:
- Add support for _Windows_.
> Release 0.1.31

- CHANGES.adoc
- go.sum
- pkg/info/info.go
- Add shortcuts for role bindings and resource quota.
- Add shortcuts for roles and SKUs.
> Release 0.1.32

- CHANGES.adoc
- pkg/info/info.go
- Update to SDK 0.1.78.
- Add quota resource name.
- Tighten up list output.
- Remove redundant `href` column from organization list.
- Add parameter usage example.
- Add organization details to account status command.
> Release 0.1.33

- CHANGES.adoc
- pkg/info/info.go
- Display quota so it supports add-ons.
> Release 0.1.35

- CHANGES.adoc
- pkg/info/info.go
The more relevant changes in the new release are the following:
- Describe by name, identifier or external identifier (fixes
https://github.com/openshift-online/ocm-cli/issues/59[#59]).
- Support query parameters in raw HTTP methods (fixes
https://github.com/openshift-online/ocm-cli/issues/6[#6]).
Related: https://github.com/openshift-online/ocm-cli/issues/59  
Related: https://github.com/openshift-online/ocm-cli/issues/6
> Release 0.1.37

- pkg/cluster/describe.go
Used to quickly determine if a cluster is public or private
> cluster describe api listening

- pkg/cluster/describe.go
> Add CCS and Cluster Admin to describe

- cmd/ocm/login/cmd.go
is there another place else I need to update?
> feat(login): add more aliases

- cmd/ocm/list/addon/cmd.go
- cmd/ocm/list/cmd.go
- pkg/cluster/cluster.go
```
./ocm list addons --cluster=irit-test2
ID               NAME             STATE
dba-operator     DBA Operator     not installed
prow-operator    Prow Operator    not installed
```
> Implement list addons

- CHANGES.adoc
- pkg/config/config.go
- pkg/info/info.go
> Assume expiration is 0 when missing in the token claim

- CHANGES.adoc
- pkg/info/info.go
- Display provision shard name in describe cluster
- Add more options to create cluster command
- Add `ocm tunnel` command
- Hide expiration time parameters in create cluster command
- Support git style ocm plugin
> Release 0.1.42

- .goreleaser.yaml
Add brews config for goreleaser: https://goreleaser.com/customization/homebrew/
cc @igoihman
> Add goreleaser config for homebrew-tap

- pkg/cluster/describe.go
* Organization Name
* Creator Email Address
> Add creator details

- pkg/cluster/describe.go
> Remove reference for BYOC in favor of CCS.Enabled

- cmd/ocm/login/cmd.go
Reverts openshift-online/ocm-cli#170
> Revert "Update integration env default url"

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/list/cmd.go
- cmd/ocm/list/region/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
- pkg/provider/regions.go
Hoping to reuse the `GetRegions()` function later for interactive `ocm create cluster`, 
as well as `moactl list regions` and `moactl create cluster --interactive` (stole much of it similar function in moactl)...
```
$ go run ./cmd/ocm list regions
Error: required flag(s) "provider" not set
exit status 1
$ go run ./cmd/ocm list regions --provider=gcp --ccs --aws-access-key-id=... --aws-secret-access-key=...
Error: identifier is '400', code is 'CLUSTERS-MGMT-400' and operation identifier is '1gb86p7kn2s4ogiq04f3fc2jpkkroa9o': Cloud provider has to be 'aws'
exit status 1
$ go run ./cmd/ocm list regions --provider=gcp 
IT                         DISPLAY NAME                        ENABLED  SUPPORTS MULTI-AZ
asia-east1                 Changhua County, Taiwan             true     true …
```
> Add `ocm list regions` command 

- cmd/ocm/create/machinepool/cmd.go
@igoihman please review, tiny followup to #164.
> update `ocm create machinepool` usage & example

- README.adoc
> Add missing API endpoint in README file

- README.adoc
This patch fixes some minor typos and _AsciiDoc_ issues in the `README.adoc` file.
> Minor fixes in `README.adoc`

- cmd/ocm/create/cluster/cmd.go
> remove duplicate import

- pkg/arguments/interactive.go
Before, this was possible if user chooses gcp then presses Enter immediately on "Region:" propmt (without moving cursor):
```
$ ./ocm create cluster foo --dry-run --interactive
? Cloud provider: gcp
? CCS: No
? Multiple AZ: No
? Region: us-east-1
Error: if specifying a non-aws cloud provider, region must be set to a valid region
```
(despite "us-east-1" NOT being one of the gcp options!  known upstream issue https://github.com/AlecAivazis/survey/pull/284)
Now with gcp the region prompt gets no default so Enter selects the first option ("asia-east1").
Partially addresses https://issues.redhat.com/browse/SDA-3524
> Avoid `survey.Select` bug when Default is not one of Options

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/interactive.go
It was only appropriate for AWS and it's good for users to make a conscious decision before creating clusters.
(This is the last part of addressing https://issues.redhat.com/browse/SDA-3524)
> Drop default of --region

- CHANGES.adoc
- pkg/info/info.go
> Update CHANGES.adoc and version info

- cmd/ocm/create/machinepool/cmd.go
Related: https://issues.redhat.com/browse/SDA-3701
> Fix example doc

- cmd/ocm/list/cluster/cmd.go
This flag better allows this command to be used in scripting
> Add flag to suppress printing of headers

- cmd/ocm/list/cluster/cmd.go
Adjust some column padding values to allow the list to display more information with less space padding.
> Adjust column padding for list

- cmd/ocm/cluster/status/status.go
- go.mod
- go.sum
The more relevant changes in the new version of the SDK are:
- support of Job Queues
- metrics moved from CS to AMS
> Update to SDK 0.1.168

- cmd/ocm/list/cmd.go
- cmd/ocm/list/quota/cmd.go
```
$ ./ocm list quota
RESERVED/ALLOWED    RESOURCE NAME                     RESOURCE TYPE               AVAILABILITY ZONE    CCS
0/15                addon-acm-operator                addon                       ANY                  false
0/15                addon-cluster-logging-operator    addon                       ANY                  false
0/15                addon-crw-operator                addon                       ANY                  false
0/15                addon-dba-operator                addon                       ANY                  false
0/15                addon-elasticsearch-operator      addon                       ANY                  false
0/15                addon-managed-api-service         addon                       ANY                  false
0/15 …
```
> Convert ocm account quota to ocm list quota command

- pkg/cluster/cluster.go
@markturansky @rawsyntax  ptal
> Modify resource_name comparison when populating add-ons

- tests/get_test.go
- tests/login_test.go
This patch adds some basic tests for the `get` command.
> Add tests for `get` command

- tests/logout_test.go
- tests/main_test.go
- tests/post_test.go
- tests/token_test.go
This patch adds some basic tests for the `post` command.
> Add tests for the `post` command

- cmd/ocm/create/idp/cmd.go
> Support specifying IdD Name

- tests/describe_cluster_test.go
This patch adds a test to verify that when a cluster has multiple
matching subscriptions the command fails and writes a message explaining
the error.
Related: https://issues.redhat.com/browse/SDA-4458
> Add test to check `describe cluster` with multiple results

- pkg/config/config.go
If the legacy ~/.ocm.json file already exists, it continues using that.
Otherwise it prefers the standard XDG config directory.
> config: Use standard config path for ocm.json

- go.mod
- go.sum
Related: https://issues.redhat.com/browse/SDA-4686
> Update to SDK 0.1.204

- .github/workflows/publish-release.yaml
- .github/workflows/requirements.txt
This patch changes the GitHub publish release action so that it
automatically adds to the release description the changs extracted from
the `CHANGES.md` file.
> Add changes to release descriptions

- CHANGES.md
- pkg/info/info.go
This version doesn't contain changes to the functionality, only to the
development and build workflows:
- Rename `master` branch to `main`.
To adapt your local repository to the new branch name run the following
commands:
```shell
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
- Automatically add changes from `CHANGES.md` to release descriptions.
> Release 0.1.60

- pkg/cluster/describe.go
Shows STS true or false based on the existence of STS information for the cluster.
> Add STS to describe cluster output

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
https://issues.redhat.com/browse/SDA-5265
> all provider's subnets are sent out in the request instead only the requested ones

- pkg/cluster/cluster.go
https://issues.redhat.com/browse/SDA-5308
> OCM-CLI: Bad Request when creating a cluster without subnet IDs

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/edit/cluster/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
- pkg/cluster/describe.go
- pkg/utils/helper.go
https://issues.redhat.com/browse/SDA-5004
https://issues.redhat.com/browse/SDA-5204
> OCM-CLI: Support cluster-wide proxy during cluster creation and update

- pkg/utils/helper.go
https://issues.redhat.com/browse/SDA-5394
> The attribute name in error message should be same with the correct proxy attribute in body

- pkg/cluster/cluster.go
https://issues.redhat.com/browse/SDA-5393
> There should be error message when create a ccs cluster with no exiting vpc but set proxy

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
sda-5428
The following are use cases for the cluster-wide-proxy feature on cluster creation via ocm-cli:
use cases for non-interactive and interactive modes:
- specifying --cluster-wide-proxy without any proxy field values will trigger prompts to the user for non-specified values. In case the user does not specify any value, it will result in an error "Expected at least one of the following: http-proxy, https-proxy, additional-trust-bundle-file".
- specifying --cluster-wide-proxy with some proxy field values, will trigger prompts to the user asking for the non-specified values.
- specifying --cluster-wide-proxy with all proxy field values, will send the request to cs with all values without any prompt
same use case with different behavior with …
> ocm-cli - Improve the cluster-wide-proxy use cases

- cmd/ocm/create/cluster/cmd.go
> It should be failed when create a non-ccs cluster with proxy attributes

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/edit/cluster/cmd.go
- cmd/ocm/list/region/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
- pkg/provider/subnetworks.go
- pkg/utils/helper.go
> ocm-cli should support byovpc and cluster-wide proxy for gcp

- pkg/dump/dump.go
@oisakov @jhernand 
Related: [SDA-5048](https://issues.redhat.com/browse/SDA-5048)
> Fix HTML escaping

- cmd/ocm/edit/cluster/cmd.go
> It should be successful to edit a ccs cluster with proxy attribute

- pkg/cluster/describe.go
> GCPNetwork attributes should show in cluster describe

- cmd/ocm/create/cluster/cmd.go
- pkg/cluster/cluster.go
This new flag allows toggling between SDN and OVN. Currently hidden
since this is not yet supported.
> Add support for selecting Network Type

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
> improving existing vpc and proxy code

- pkg/cluster/describe.go
> added account number to "ocm describe cluster <cluster_num>

- README.md
> Correct the ocm json location in mac

- CHANGES.md
- pkg/info/info.go
- Improve existing VPC and proxy code.
- Disable color in Windows.
- Added account number to "ocm describe cluster ...".
- Show limited support flag in "ocm describe cluster ...".
> Release 0.1.63

- pkg/cluster/cluster.go
> better error when gcp ccs creds are not provided

- pkg/cluster/cluster.go
- tests/describe_cluster_test.go
https://issues.redhat.com/browse/SDA-5813
> SDA-5813 - Remove DisplayName/display_name from cluster

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/edit/cluster/cmd.go
- pkg/arguments/arguments.go
- pkg/cluster/cluster.go
- pkg/cluster/describe.go
- pkg/utils/helper.go
> Add no-proxy attribute to OCM-CLI

- cmd/ocm/create/cluster/cmd.go
> adding an error when proxy is set for non byo-vpc cluster creation

- pkg/cluster/cluster.go
> Fix GetCluster AMS search

- cmd/ocm/edit/cluster/cmd.go
> Fix edit cluster command

- README.md
Adding my tap is no longer required :)
> Update brew installation instructions

- README.md
> Update revocation link

- README.md
The _copr_ builds have been failing for some time because the build was using an old version of the Go compiler. This patch fixes that. Nnote that these instructions aren't copied automatically to _copr_, the have been copied manually.
> Update _copr_ build instructions

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/edit/ingress/cmd.go
- go.mod
- go.sum
- pkg/cluster/cluster.go
Related issue: https://issues.redhat.com/browse/OCM-2657
> OCM-2657 | feat: day1/2 operations for managed ingress attributes

- cmd/ocm/create/cluster/cmd.go
- cmd/ocm/edit/ingress/cmd.go
Related issue: https://issues.redhat.com/browse/OCM-2941
> OCM-2941| fix: Adjusting help usage and ingress builder call

- cmd/ocm/create/cluster/cmd.go
- pkg/arguments/interactive.go
> OCM-4183 | feat: suggest pop out an error message instead of stop the progress if user do not input the service account file

- CHANGES.md
- pkg/info/info.go
- OCM-4750 | feat: additional security group ids attributes
> Release v0.1.71

- cmd/ocm/login/cmd.go
- go.mod
- go.sum
> OCM-5759 | feat: Add Device Code Flow

- docker/Dockerfile
https://issues.redhat.com/browse/OCM-7821
> OCM-8013| feat: Dockerfile for Konflux builds

- .tekton/ocm-cli-pull-request.yaml
- .tekton/ocm-cli-push.yaml
pipeline Customizations need to happen after initial merge from Konflux
> Trigger pipeline only if event title starts with Konflux

- cmd/ocm/gcp/create-wif-config.go
- cmd/ocm/gcp/gcp.go
- go.mod
- go.sum
Related issue: https://issues.redhat.com/browse/OCM-10458
> Add role prefix flag on create wif-config

- cmd/ocm/list/addon/cmd.go
- go.mod
- go.sum
- pkg/cluster/cluster.go
- pkg/urls/url_expander.go
This is to resolve OCM-1983, to update the cli to list addons with ocm-addon-service API
> Update to use addon service API for addons function

- CHANGES.md
- pkg/info/info.go
-9fbb753 Update to use addon service API for addons function 
-1bafd65 Add command 'gcp verify wif-config' (#691) 
-5d0bec1 Update Konflux references (#682)
-f0ed911 OCM-12467 | feat : Updates for binaries-release-pipeline (#693) 
-c42c641 Update Konflux references (#694)
> Release v1.0.3

- cmd/ocm/create/cluster/cmd.go
- pkg/cluster/cluster.go
- pkg/provider/encryption.go
Ref: https://issues.redhat.com/browse/OCM-11995
The file shows "some" of the  several +ve and -ve tests run to verify 
[tests.txt](https://github.com/user-attachments/files/18443091/tests.txt)
> OCM-11995 | feat : Add GCP KMS custom encryption support

- .tekton/ocm-cli-push.yaml
Additional changes required for the latest konflux build pipelines to run successfully
> updates to konflux_build_pipeline

- cmd/ocm/gcp/update-wif-config.go
Ref: https://issues.redhat.com/browse/OCM-14062 for details 
Test Log
[test.log](https://github.com/user-attachments/files/18968257/test.log)
> N-3 vesion support for  wif

- CHANGES.md
- pkg/info/info.go
-3a8ef75 OCM-12971 | 'ocm gcp update wif-config' remediates all wif-config misconfigurations (#696) -d4deb29 Add 'version' flag to wif-config create and update commands (#698) -f079176 updated help message for wif verification errors -1fb1d56 Refactored GCP client operations to log user messages and optimized resource updation (#700) -dd04c33 Update Konflux references (#697)
-c84225e OCM-11995 | feat : Add GCP KMS custom encryption support (#701) -7ac7051 added 'availability-zone' argument to machine pool creation (#703) -56ca538 updates to konflux_build_pipeline (#704)
-b37893c listing wif-configs shows supported versions (#706) -7087572 Update Konflux references (#702)
-7aac46f Update Konflux references (#707)
-2045f98 Update github.com/pkg/browser digest to 5ac0b6a (#708) -0b6615a …
> Release v1.0.4

- go.mod
- go.sum
To test these changes, a wif-config was created, and then a wif cluster was deployed. These resources were then deleted. The attached file shows these tests being run.
[OCM-14780-test.txt](https://github.com/user-attachments/files/19595457/OCM-14780-test.txt)
> Update module github.com/golang-jwt/jwt/v4 to v4.5.2

- cmd/ocm/gcp/describe-wif-config.go
ckandaga@ckandaga-mac ocm-cli-ck % ./ocm gcp describe wif-config 2hs9nd3vhccen58i25sivlp9d1b1k5e0
ID:            2hs9nd3vhccen58i25sivlp9d1b1k5e0
Display Name:  cktest-ccs3
Project:       sda-ccs-3
Issuer URL:    https://openshift.com
Versions:      [v4.18 v4.17]
> OCM-15037 | display versions on wif-config describe

- CHANGES.md
- pkg/info/info.go
-8e28c06 OCM-14358 | unbind service accounts when deleting wif-configs (#723) -62f7db3 Improving UX around gcloud iam api consistency model (#725) -a8ab357 OCM-14357 | Ensuring wif commands are resilient to GCP's consistency model (#726) -c41ad70 Update module github.com/golang-jwt/jwt/v4 to v4.5.2 (#727) -19bb541 Update module github.com/hashicorp/go-version to v1.7.0 (#724) -d4b073f Update Konflux references (#712)
-3d30c1c Update module github.com/spf13/pflag to v1.0.6 (#717) -5010823 Update module github.com/openshift-online/ocm-sdk-go to v0.1.463 (#715) -22467d1 various cve updates (#731)
-7deabe5 display versions on wif-config describe (#732)
> Release v1.0.5

- .tekton/ocm-cli-push.yaml
Konflux pipelines now require for two additional tasks to be added
> Updates to konflux pipeline for cli release 1.0.5

- cmd/ocm/create/machinepool/cmd.go
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create machinepool --help
--secure-boot-for-shielded-vms            Secure Boot enables the use of Shielded VMs in the Google Cloud Platform for the instances in this machine pool. This will override the cluster level configuration of secure boot.
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create machinepool mipereir-test-aws --cluster=2ip9nqc8b55moho2fgt9j8dovsaj8kt1  --instance-type=m5.xlarge --replicas=1 --secure-boot-for-shielded-vms=false
Error: --secure-boot-for-shielded-vms is only supported for clusters using the 'gcp' cloud provider
mipereir@mipereir-thinkpadp1gen4i:~/myprojects/ocm-cli$ ./ocm create machinepool mipereir-test --cluster=2ipbp1nn1162fjnf9aemnuqrgtaf3uri --instance-type=n2-standard-4 …
> OCM-13205 | secure-boot-for-shielded-vms flag for create machinepool

- cmd/ocm/create/machinepool/verification_test.go
=== RUN   TestMachinepool
Running Suite: Machinepool Suite - /home/mipereir/myprojects/ocm-cli/cmd/ocm/create/machinepool
Random Seed: 1747351822
Will run 14 of 14 specs
••••••••••••••
Ran 14 of 14 Specs in 0.002 seconds
SUCCESS! -- 14 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestMachinepool (0.00s)
PASS
ok      github.com/openshift-online/ocm-cli/cmd/ocm/create/machinepool
> OCM-13205 |  unit tests for the machinepool secure-boot-for-shielded-vms flag

- README.md
Update the Go version in COPR - updating the Readme to match the version that is now running there.
> Update README.md spec-file
